### ISSUE TITLE
egressd exporter deployment has typo on conditional cast apiKey

### ISSUE THREAD

**Issue by jsanghi** [castai/egressd#55]
https://github.com/castai/egressd/blob/013f057aa2c80fb86bf7d2433e084ac4b21f7476/charts/egressd/templates/exporter/deployment.yaml#L52C18-L52C18

This conditional doesn't seem to work.  Needs a space between `if` and `.Values`

**Comment by Ayush9026** [comment]
@jsanghi sir i'll fix this issue.
