### ISSUE TITLE
Exporter's deployment template is not using resources from values

### ISSUE THREAD

**Issue by Israphel** [castai/egressd#62]
This: https://github.com/castai/egressd/blob/v0.10.3/charts/egressd/values.yaml#L136

doesn't seem to be referenced here: https://github.com/castai/egressd/blob/v0.10.3/charts/egressd/templates/exporter/deployment.yaml

**Comment by RomanMelnyk113** [comment]
@Israphel thanks for lettings us know, it was fixed in `v0.10.4`. Please check https://github.com/castai/egressd/blob/v0.10.4/charts/egressd/templates/exporter/deployment.yaml#L40

**Comment by Israphel** [comment]
but what's the chart's version with the fix? isn't the latest chart still 0.1.19?
